### ISSUE TITLE
NOT an issue with the code: Noob Question

### ISSUE THREAD

**Issue by MZULALI** [Toroi01/TradingRLBot#51]
Slight noob question here. I am very interested in RL, especially in the crypto/finance area and I was curious to know what the current programs look like.

I've initiated the Conda env and installed all the requirements, I am just having trouble finding out how to start one of the three RL methods.

Again, not a problem with the code, rather a noob trying to learn the ropes.

**Comment by Toroi01** [comment]
Hello  MZULALI,
If you want to test the models you should execute TradingRLBot/src/scripts/test.py, be aware that in this script we used the variable BEST_MODEL_NAME which is defined in TradingRLBot/src/config/config.py and his default value is "ddpg", if you want to test dqn or ppo just change the BEST_MODEL_NAME.

**Comment by Toroi01** [comment]
Btw thanks for your comment. We have updated the README to clarify this issue.

**Comment by MZULALI** [comment]
Hi,
Thank you for the clarification and appreciate the fast response. But I ran into another problem while executing test.py.

`
TradingRLBot/lib/python3.9/site-packages/pyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  warnings.warn(
INFO:root:Loading dataset
`

`
Downloaded https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1h/BTCUSDT-1h-2020-01.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/ETHUSDT/1h/ETHUSDT-1h-2020-01.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/BNBUSDT/1h/BNBUSDT-1h-2020-01.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/ADAUSDT/1h/ADAUSDT-1h-2020-01.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/XRPUSDT/1h/XRPUSDT-1h-2020-01.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/DOGEUSDT/1h/DOGEUSDT-1h-2020-01.zip `

...

`
Downloaded https://data.binance.vision/data/spot/monthly/klines/LINKUSDT/1h/LINKUSDT-1h-2021-05.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/LTCUSDT/1h/LTCUSDT-1h-2021-05.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1h/BTCUSDT-1h-2021-06.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/ETHUSDT/1h/ETHUSDT-1h-2021-06.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/BNBUSDT/1h/BNBUSDT-1h-2021-06.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/ADAUSDT/1h/ADAUSDT-1h-2021-06.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/XRPUSDT/1h/XRPUSDT-1h-2021-06.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/DOGEUSDT/1h/DOGEUSDT-1h-2021-06.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/LINKUSDT/1h/LINKUSDT-1h-2021-06.zip
Downloaded https://data.binance.vision/data/spot/monthly/klines/LTCUSDT/1h/LTCUSDT-1h-2021-06.zip
`
...
After executing the code it downloads the data but continually loads. 

I figured it was the zipline.assets warning which seems to be a problem with pyfolio. Any idea on what causes this?

**Comment by Toroi01** [comment]
It takes a while doing the feature engineering to the whole dataset, if you want you can change the START_DATE and END_DATE variables located in the config.py to have fewer data to preprocess.

**Comment by MZULALI** [comment]
yep yep yep, you're right, I should've been more patient. Nothing wrong with the code. But bear with me, I have one more question. After everything is set up, the program starts but I instantly get this error
```
 TradingRLBot/lib/python3.9/site-packages/pyfolio/pos.py:26: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
warnings.warn(
INFO:root:Loading dataset
INFO:root:Loading the best model
Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
INFO:root:Testing the best model
Test from [2021-04-01 00:00:00] to [2021-05-31 23:00:00]
RESET
RESET
Illegal instruction (core dumped)
```

I was having trouble finding the cause of the dump. Do you have any ideas?

**Comment by Toroi01** [comment]
No idea,  can you test it in a computer with a gpu?

**Comment by MZULALI** [comment]
My machine does have a GPU, don't know why the CPU is acting up. 

Thanks for the help, any issues beyond this is probably just my machine set up. If you have any suggestions please throw them my way.

**Comment by MZULALI** [comment]
sorry for bad english

what computer specifications do you recommend for this program?
